name: Update Wallpaper Daily

on:
  schedule:
    # Runs at 09:30 UTC (3:00 PM IST) and 21:30 UTC (3:00 AM IST)
    - cron: '30 9,21 * * *'
  workflow_dispatch: # Allows you to run it manually to test

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Generate Wallpaper
      run: node update-wallpaper.js

    - name: Commit and Push New Image
      run: |
        git config --global user.name 'Gita Bot'
        git config --global user.email 'bot@bhgvd.com'
        git add wallpaper.png
        git commit -m "New Daily Wallpaper [skip ci]" || echo "No changes to commit"
        git push